#!/bin/sh

export DOTNET_CLI_TELEMETRY_OPTOUT=1
export PATH="${PATH}:${HOME}/.local/bin/"
export PATH="$PATH:${HOME}/.dotnet/tools"
export PATH="$PATH:${HOME}/.cargo/bin"
export ZSH="${HOME}/.oh-my-zsh"
export TERM=xterm-256color
export MONITOR=eDP

#BSPWM configuration
bspc config border_width         1
bspc config window_gap           0
bspc config top_padding          22
bspc config bottom_paddin        0       
bspc config left_padding         0
bspc config right_padding        0
bspc config single_monocle       false
bspc config click_to_focus       true
bspc config split_ratio          0.51
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config focus_follows_pointer true
bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color 	"#dd2727"


#Single monitor
bspc monitor -d          

#Fullscreen applications
bspc rule -a Gimp state=fullscreen

#Floating applications
bspc rule -a feh state=floating
bspc rule -a mpv state=floating sticky=on
bspc rule -a Pavucontrol state=floating sticky=on
bspc rule -a Peek state=floating

#Tiled applications
bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled

bspc rule -a Chromium desktop='^2'  follow=off
bspc rule -a Code desktop='^1' follow=off
bspc rule -a Steam desktop='^8' follow=off state=floating
bspc rule -a mpv desktop='^6' follow=on
bspc rule -a discord desktop='^4' follow=off
bspc rule -a Thunderbird desktop='^5' follow=off
bspc rule -a Pulseeffects desktop='^10' follow=off


#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_eDP)

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh