#!/bin/sh

#BSPWM configuration
bspc config border_width        1
bspc config window_gap			12
bspc config top_padding         24
bspc config split_ratio         0.51

bspc config single_monocle      true
bspc config borderless_monocle  true

bspc config history_aware_focus true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color 	"#dd2727"


#Single monitor
bspc monitor -d          

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_eDP)

bspc config external_rules_command $HOME/.config/bspwm/externalRules/external_rules.csx

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh
