#!/bin/sh

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_eDP)

bspc config external_rules_command $HOME/.config/bspwm/externalRules/external_rules.csx

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh
