#!/bin/bash

wid="$1"
class="$2"
wid="test"
echo "$wid" | tee /tmp/wid

case "$class" in
	Chromium )
		for "$(xprop -id "$wid" _NET_WM_WINDOW_TYPE)" in *_NET_WM_WINDOW_TYPE_DIALOG* do
			echo "state=fullscreen" 
		done ;;
    Geary )
		for "$(xprop -id "$wid" _NET_WM_WINDOW_TYPE)" in *_NET_WM_WINDOW_TYPE_DIALOG*
		do
			echo "state=fullscreen" 
		done ;;
    Steam )
		for "$(xprop -id "$wid" _NET_WM_WINDOW_TYPE)" in *_NET_WM_WINDOW_TYPE_DIALOG*
		do
			echo "state=fullscreen"
		done ;;
esac